name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: deploy
        uses: dark-flames/apollo-typst@action-v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: static
        # deploy-repo: ${{ another/repo }}