name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: deploy
        uses: dark-flames/apollo-typst@action-v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: static
        # deploy-repo: ${{ another/repo }}